#!/bin/bash

cd .client
cp device_key_encrypted.dat ../.server/
cd ../.server/
sudo bash decrypt-key.sh
cp device_key.dat ../.client/
cd ..
echo "We have recieved your payment, you can now decrypt your files"
